// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgzmhqtsbqejkymebmze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnem1ocXRzYnFlamt5bWVibXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTQzMzQsImV4cCI6MjA1NzI5MDMzNH0.w4JFj3WXjAcND-0Eo5mN_gnUCliD6F-GUTEiEFRpIRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);